server:
  port: 8080
  servlet:
    context-path: /mall/admin

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bro_dog_mall?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Aa123456
    type: com.alibaba.druid.pool.DruidDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/xml/*Mapper.xml